### ISSUE TITLE
How to install grails in ECLIPSE?

### ISSUE THREAD

**Issue by chaitanya9249** [spring-projects/grails-ide#9]
HI
I have installed groovy in eclipse successfully.But While I was searching for grails to set version 2.4.2 i can't see that in windows===>Preferences.

Please let me know if you have any idea about this.

**Comment by martinlippert** [comment]
As described in this issue here:
https://github.com/spring-projects/grails-ide/issues/7

The Grails IDE project is no longer under active development. Therefore it hasn't got any updates for the latest versions of Eclipse and I don't think it is compatible anymore with the most recent versions of Eclipse.

You can try to use an older version of Eclipse and install everything in there or grab the last version of the Groovy-Grails-Tool-Suite from here: https://spring.io/tools/ggts/all - it is a ready-to-use Eclipse distribution with Groovy-Eclipse and Grails-IDE pre-installed. But again, it is an old version that is no longer maintained...
